baseURL = 'https://astrikos.github.io'
languageCode = 'en-us'
title = 'Andreas Strikos'
theme = "ink-free"

paginate = 5

# copyright = "© Copyright notice"

[permalinks]
  posts = "/:year/:month/:title"

[params]
	subtitle = "Software and Infrastructure Engineer"

	# Optional 64x64 avatar image.
	avatar = "/boy-student-sitting.webp"

	featherIconsCDN = false

	# Site color - dark/light/auto
	mode = "auto"

	# Enable a table of contents
	toc = false

	# Max tags
	maxTags = 7

	# Define words per minute to approximate reading time
	wpm = 250

	# Github base url
	# github = "https://github.com/astrikos"


# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

# [[menu.main]]
# name = "About"
# url = "/about"
# weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/astrikos"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/astrikos/"

[taxonomies]
   tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4
